// decode module
// takes instructions in, splits them into control signals

module decode
import riscv_pkg::*;
import csr_pkg::*;
(
    input clk_i,
    input rstn_i,
    input instr_valid_i,

    // from csr unit
    input priv_lvl_e current_plvl_i,

    // register file <-> decode module
    // read port
    output [4:0] regf_rs1_addr_o,
    output [4:0] regf_rs2_addr_o,
    input [31:0] rs1_data_i,
    input [31:0] rs2_data_i,

    // csr unit <-> decode module
    // read port
    output csr_re_o, // read enable

    // from IF stage
    input [31:0] instr_i, // instruction

    // ID/EX pipeline registers

    // feedback into the pipeline register
    input stall_i, // keep the same content in the registers
    input flush_i, // zero the register contents

    // for direct use by the EX stage
    output logic [31:0] rs1_data_o,
    output logic [31:0] rs2_data_o,
    output logic [31:0] imm_o,
    output alu_oper1_src_t alu_oper1_src_o,
    output alu_oper2_src_t alu_oper2_src_o,
    output bnj_oper_t bnj_oper_o,
    output alu_oper_t alu_oper_o,

    output logic is_muldiv_instrE_o, // is the instruction a mul/div instruction?

    // traps generated by this stage
    output logic illegal_instrD_o,

    // for the MEM stage
    output mem_oper_t mem_opD_o,
    output atomic_op_e atomic_opD_o,
    output logic csr_we_o,

    // for the WB stage
    output result_src_e result_srcE_o,
    output logic write_rdD_o,
    output logic [4:0] rdD_o,

    // used by the hazard/forwarding logic
    output logic [4:0] rs1_addr_o,
    output logic [4:0] rs2_addr_o,

    output exc_t sys_instrE_o,
    output fence_t fenceE_o
);

// extract the common fields from the instruction format
opcode_t opcode;
logic [4:0] rs1, rs2, rdD;
logic [2:0] func3;
logic [6:0] func7;

assign opcode = opcode_t'(instr_i[6:0]);
assign rdD = instr_i[11:7];
assign rs1 = instr_i[19:15];
assign rs2 = instr_i[24:20];
assign func3 = instr_i[14:12];
assign func7 = instr_i[31:25];

wire is_func7_zero = (func7 == '0);
wire is_func7_sub_sra = (func7 == 7'b0100_000);
wire is_func7_muldiv = (func7 == 7'b0000_001);

wire is_r_type = ((func3 == 3'b101 | func3 == 3'b000) & is_func7_sub_sra) | is_func7_zero;

wire is_imm_arith_no_shift = (func3 != 3'b101 & func3 != 3'b001);
// arithmetic immediates and arithmetic immediate shifts use different formats
wire is_imm_arith_shift = ((func3 == 3'b001) & is_func7_zero) |
                         ((func3 == 3'b101) & (is_func7_zero | is_func7_sub_sra));

wire is_imm_arith = is_imm_arith_no_shift | is_imm_arith_shift;

wire [4:0] upper_5 = instr_i[31:27];
// or all the possible valid 5 MSB combination for AMO instructions
wire is_valid_amo = (upper_5 == 5'b00001) |
                    (upper_5 == 5'b00000) |
                    (upper_5 == 5'b00100) |
                    (upper_5 == 5'b01100) |
                    (upper_5 == 5'b01000) |
                    (upper_5 == 5'b10000) |
                    (upper_5 == 5'b10100) |
                    (upper_5 == 5'b11000) |
                    (upper_5 == 5'b11100);

// immediates
logic [31:0] imm_i, imm_s, imm_b, imm_u, imm_j, imm_csr;

assign imm_i = 32'(signed'(instr_i[31:20]));
assign imm_s = 32'(signed'({instr_i[31:25], instr_i[11:7]}));
assign imm_b = 32'(signed'({instr_i[31], instr_i[7], instr_i[30:25], instr_i[11:8], 1'b0}));
assign imm_u = {instr_i[31:12], 12'b0};
assign imm_j = 32'(signed'({instr_i[31], instr_i[19:12], instr_i[20], instr_i[30:21], 1'b0}));
assign imm_csr = 32'({instr_i[19:15]}); // used for immediate csr instructions

alu_oper_t alu_oper;
logic [31:0] curr_imm;
logic write_rdD;
result_src_e result_srcD;

alu_oper1_src_t alu_oper1_src;
alu_oper2_src_t alu_oper2_src;

bnj_oper_t bnj_oper;
mem_oper_t mem_operD; // memory operation if any

atomic_op_e atomic_opD;
logic is_muldiv_instrD;
exc_t sys_instrD;
fence_t fenceD;
logic csr_re;
logic csr_we;

// decode
always_comb
begin : main_decode

    alu_oper1_src = OPER1_RS1;
    alu_oper2_src = OPER2_RS2;

    write_rdD = '0;
    result_srcD = RESULT_ALU;
    curr_imm = '0;
    bnj_oper = BNJ_NO; // no branch

    mem_operD = '{
        mem_rw: 2'b00,
        is_load_unsigned: func3[2],
        mem_width: func3[1:0]
    };

    sys_instrD = NO_SYS;
    fenceD = NO_FENCE;
    csr_re = '0;
    csr_we = '0;

    atomic_opD = NO_ATOMIC;
    is_muldiv_instrD = 1'b0;
    illegal_instrD_o = 1'b0;

    // zero out control signals when the instruction being fed in is not valid
    // could avoid some read side effects in some registers in the future
    if (instr_valid_i)
        case (opcode)
            LUI:
            begin
                alu_oper1_src = OPER1_ZERO;
                alu_oper2_src = OPER2_IMM;

                curr_imm = imm_u;
                write_rdD = 1;
            end

            AUIPC:
            begin
                alu_oper1_src = OPER1_PC;
                alu_oper2_src = OPER2_IMM;

                curr_imm = imm_u;
                write_rdD = 1;
            end

            JAL:
            begin
                alu_oper1_src = OPER1_PC;
                alu_oper2_src = OPER2_PC_INC;

                curr_imm = imm_j;
                write_rdD = 1;
                bnj_oper = BNJ_JAL;
            end

            JALR:
            begin
                alu_oper1_src = OPER1_PC;
                alu_oper2_src = OPER2_PC_INC;
                
                curr_imm = imm_i;
                write_rdD = 1;
                bnj_oper = BNJ_JALR;
            end

            BRANCH:
            begin
                curr_imm = imm_b;
                bnj_oper = BNJ_BRANCH;
            end

            LOAD:
            begin
                alu_oper2_src = OPER2_IMM;
                curr_imm = imm_i;

                write_rdD = 1;
                result_srcD = RESULT_MEM;

                mem_operD.mem_rw = 2'b10;
            end

            STORE:
            begin
                alu_oper2_src = OPER2_IMM;
                curr_imm = imm_s;

                mem_operD.mem_rw = 2'b01;
            end

            ARITH:
            begin
                write_rdD = 1;
                
                if (is_func7_muldiv) begin
                    is_muldiv_instrD = 1'b1;
                    result_srcD = RESULT_MDU;
                end else if (!is_r_type) begin
                    illegal_instrD_o = 1'b1;
                end
            end

            ARITH_IMM:
            begin
                alu_oper2_src = OPER2_IMM;
                curr_imm = imm_i;
                write_rdD = 1;

                if (!is_imm_arith) begin
                    illegal_instrD_o = 1'b1;
                end
            end

            FENCE:
            begin
                case (func3)
                    3'b000:
                        fenceD = FENCE_D;
                    3'b001:
                        fenceD = FENCE_I;
                    default:
                        illegal_instrD_o = 1'b1;
                endcase
            end

            SYSTEM:
            begin
                if (func3 == '0 && rdD == '0) // ecall, ebreak or mret
                begin
                    if (func7 == 7'b0011000) // mret
                        sys_instrD = MRET;
                    else
                    begin
                        if (instr_i[31:20] == 12'd1)
                            sys_instrD = BRK_POINT;
                        else
                            sys_instrD = (current_plvl_i == PRIV_LVL_M) ? ECALL_MMODE : ECALL_UMODE;
                    end
                end
                else  // CSR instruction
                begin
                    write_rdD = 1'b1;
                    result_srcD = RESULT_CSR;
                    // determine if csr will be read
                    // In CSRRW*: if rd = Zero, the csr is not read and any read side-effects will not be triggered
                    // csr_re = ((system_opc_t'(func3) == CSRRW ||
                        // system_opc_t'(func3) == CSRRWI) && rd == '0) ? 1'b0 : 1'b1;
                    csr_re = 1'b1; // doesn't matter since no CSRs have side effects, + is crucial for illegalcsr access in cs_registers

                    // determine is csr will be written
                    // In CSRRS/C: If rs1 = Zero, the csr is not written and any write side-effect will not be triggered
                    // In CSRRSI/CI: If uimm = Zero, the csr is not written any write side-effects will not be triggered
                    csr_we = ((rs1 == '0 && (system_opc_t'(func3) == CSRRS || system_opc_t'(func3) == CSRRS)) ||
                        (imm_csr == '0 && (system_opc_t'(func3) == CSRRSI || system_opc_t'(func3) == CSRRCI))) ? 1'b0 : 1'b1;
                end
            end

            ATOMIC: begin
                alu_oper2_src = OPER2_ZERO;
                write_rdD = 1'b1;

                // LR.D
                if ((instr_i[24:20] == 5'b0) & (upper_5 == 5'b00010)) begin
                    atomic_opD = ATOMIC_LR;
                    result_srcD = RESULT_MEM;

                    mem_operD.mem_rw = 2'b10;
                end else if ((upper_5 == 5'b00011)) begin  // SC.D
                    result_srcD = RESULT_SC;
                    atomic_opD = ATOMIC_LR;

                    mem_operD.mem_rw = 2'b01;
                end else if (is_valid_amo) begin
                    result_srcD = RESULT_MEM;
                    mem_operD.mem_rw = 2'b11;
                    atomic_opD = ATOMIC_AMO;
                end else begin
                    illegal_instrD_o = 1'b1;
                end
            end

            default: begin
                illegal_instrD_o = 1'b1;
            end
        endcase
end

// decoding the alu operations separately

always_comb
begin : alu_decode
    alu_oper = ALU_ADD;

    case(opcode)
        JAL, JALR, LOAD, STORE, AUIPC:
        begin
            alu_oper = ALU_ADD;
        end

        BRANCH:
        begin
            if (opcode_branch_t'(func3) == BNE)
                alu_oper = ALU_SNEQ;
            else if (opcode_branch_t'(func3) == BEQ)
                alu_oper = ALU_SEQ;
            else
            begin
                alu_oper = alu_oper_t'({func3[0], 1'b0, func3[2:1]});
            end
        end

        ARITH:
        begin
            alu_oper = alu_oper_t'({instr_i[30],func3});
        end

        ARITH_IMM:
        begin
            if (opcode_alu_t'(func3) == SRA_L)
                alu_oper = alu_oper_t'({instr_i[30],func3});
            else
                alu_oper = alu_oper_t'({1'b0,func3});
        end

        SYSTEM:
        begin
        end

        default: // no need to handle anything here, already handled illegal opcodes above
        begin end
    endcase
end

// pipeline registers and outputs

assign regf_rs1_addr_o = rs1;
assign regf_rs2_addr_o = rs2;
assign csr_re_o = csr_re;
assign mem_opD_o = mem_operD;
assign atomic_opD_o = atomic_opD;

flopenrc #(1) pipeline (clk_i, rstn_i, flush_i, ~stall_i, is_muldiv_instrD, is_muldiv_instrE_o);

always_ff @(posedge clk_i)
begin : id_ex_pip
    if (!rstn_i || flush_i)
    begin
        rs1_data_o <= 0;
        rs2_data_o <= 0;
        imm_o <= 0;
        // csr_rdata_o <= 0;
        alu_oper1_src_o <= OPER1_RS1;
        alu_oper2_src_o <= OPER2_RS2;
        bnj_oper_o <= BNJ_NO;
        alu_oper_o <= ALU_ADD;

        csr_we_o <= 0;

        result_srcE_o <= RESULT_ALU;

        rs1_addr_o <= 0;
        rs2_addr_o <= 0;

        sys_instrE_o <= NO_SYS;
        fenceE_o <= NO_FENCE;
    end
    else if (!stall_i)
    begin
        rs1_data_o <= rs1_data_i;
        rs2_data_o <= rs2_data_i;
        imm_o <= curr_imm;
        // csr_rdata_o <= csr_rdata_i;
        alu_oper1_src_o <= alu_oper1_src;
        alu_oper2_src_o <= alu_oper2_src;
        bnj_oper_o <= bnj_oper;
        alu_oper_o <= alu_oper;

        csr_we_o <= csr_we;

        result_srcE_o <= result_srcD;

        rs1_addr_o <= rs1;
        rs2_addr_o <= rs2;

        sys_instrE_o <= sys_instrD;
        fenceE_o <= fenceD;
    end
end

assign write_rdD_o = write_rdD;
assign rdD_o = rdD;

endmodule: decode
